extends:
  - stylelint-config-standard
  - stylelint-config-prettier

plugins:
  - stylelint-scss

rules:
  at-rule-no-unknown:
    - null
  property-no-unknown:
    - true
    - ignoreProperties:
        - content-visibility
  scss/at-rule-no-unknown:
    - true
