references:
  docker-init: &docker-init
    entrypoint:
      - docker-init
      - --
      - /docker-entrypoint.sh
    cmd:
      - /bin/sh

  on-tagged-version: &on-tagged-version
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v.*/

  base: &base
    docker:
      - image: circleci/node:10.15.3-browsers
        <<: *docker-init
    working_directory: ~/marp-cli
    steps:
      - run: node --version
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-{{ .Branch }}
            - dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-
            - dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-

      - run: yarn install
      - run: yarn audit

      - save_cache:
          key: dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-{{ .Branch }}
          paths:
            - node_modules
            - ~/.cache/yarn

      - run:
          name: Prettier formatting
          command: yarn format:check

      - run:
          name: TypeScript type checking
          command: yarn check:ts

      - run:
          name: TSLint
          command: yarn lint:ts

      - run:
          name: stylelint
          command: yarn lint:css

      - run:
          name: Jest
          command: yarn test:coverage --ci -i --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: tmp/test-results/jest.xml

      - run: yarn codecov

      - store_test_results:
          path: tmp/test-results

      - store_artifacts:
          path: ./coverage
          destination: coverage

version: 2
jobs:
  current:
    <<: *base

  carbon:
    <<: *base
    docker:
      - image: circleci/node:carbon-browsers
        <<: *docker-init

  docker-image:
    docker:
      - image: docker:git
    working_directory: ~/marp-cli
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker image
          command: docker build --no-cache -t marpteam/marp-cli:latest .

      - run:
          name: Push to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push marpteam/marp-cli:latest

  standalone-build:
    <<: *base
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-{{ .Branch }}
            - dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-
            - dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-

      - run: yarn install
      - run: yarn build:standalone

      - persist_to_workspace:
          root: ./bin
          paths:
            - '*'

      - store_artifacts:
          path: ./bin
          destination: bin

  github-release:
    <<: *base
    steps:
      - checkout

      - attach_workspace:
          at: ./bin

      - run:
          name: Create release and upload binaries on GitHub
          command: |
            RELEASE_ID=$(curl -sS https://raw.githubusercontent.com/marp-team/marp/master/github-release.js | node) && \
            ENDPOINT="https://uploads.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/${RELEASE_ID}/assets" && \
            curl -sS --data-binary @"bin/marp-cli-linux" -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" -H "Content-Type: application/octet-stream" ${ENDPOINT}?name=marp-${CIRCLE_TAG}-linux && \
            curl -sS --data-binary @"bin/marp-cli-macos" -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" -H "Content-Type: application/octet-stream" ${ENDPOINT}?name=marp-${CIRCLE_TAG}-mac && \
            curl -sS --data-binary @"bin/marp-cli-win.exe" -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" -H "Content-Type: application/octet-stream" ${ENDPOINT}?name=marp-${CIRCLE_TAG}-win

workflows:
  version: 2
  build:
    jobs:
      - current
      - carbon
      - docker-image:
          requires:
            - current
            - carbon
          filters:
            branches:
              only: master
      - standalone-build:
          <<: *on-tagged-version
      - github-release:
          <<: *on-tagged-version
          context: github-release
          requires:
            - standalone-build
