name: Release for Windows

on:
  push:
    tags:
      - v*

jobs:
  win-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.0'
      - name: Install with yarn
        run: npm install -g yarn && yarn install
      - name: Build and create standalone binaries
        run: yarn build:standalone
      - name: Create package for Windows
        run: yarn standalone:pack
        env:
          TARGET: win
      - name: Upload created package to the asset of GitHub release
        run: yarn standalone:pack:upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
