on: push

jobs:
  win-test:
    runs-on: windows-2016

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 8.x
          - '10.16.0'
          - 12.x

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install with yarn
        run: npm install -g yarn && yarn install
      - name: Jest
        run: yarn test:coverage --ci -i --reporters=default --reporters=jest-junit
        env:
          CI: true
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: windows
