name: Test for Windows

on:
  - pull_request
  - push

env:
  YARN_VERSION: '^1.22.5'

jobs:
  win-test:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - '^12.20.0'
          - '14.17.3'
          - '^16.0.0'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        id: yarn
        run: |
          cd $HOME && yarn policies set-version $YARN_VERSION
          echo "::set-output name=cache_dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn.outputs.cache_dir }}
          key: yarn_cache-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn_cache-${{ runner.os }}-${{ matrix.node-version }}-
            yarn_cache-${{ runner.os }}-

      - name: Install dependencies with yarn
        run: yarn install

      # Retry tests up to 3 times due to flaky tests on Windows CI
      # https://stackoverflow.com/a/59365905
      - name: Jest
        run: >-
          yarn test:coverage --ci -i --reporters=default --reporters=jest-junit ||
          yarn test:coverage --ci -i --reporters=default --reporters=jest-junit --no-cache ||
          yarn test:coverage --ci -i --reporters=default --reporters=jest-junit --no-cache
        env:
          CI: true

      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage

      - name: Codecov
        run: yarn codecov -F windows
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
