name: Test for Windows

on:
  - pull_request
  - push

env:
  YARN_VERSION: '^1.22.5'

jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || !startsWith(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  win-test:
    runs-on: windows-latest
    needs: validate

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - '^10.17.0'
          - '^12.20.0'
          - '14.15.1'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        id: yarn
        run: |
          cd $HOME && yarn policies set-version $YARN_VERSION
          echo "::set-output name=cache_dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn.outputs.cache_dir }}
          key: yarn_cache-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn_cache-${{ runner.os }}-${{ matrix.node-version }}-
            yarn_cache-${{ runner.os }}-

      - name: Install dependencies with yarn
        run: yarn install

      - name: Jest
        run: yarn test:coverage --ci -i --reporters=default --reporters=jest-junit
        env:
          CI: true

      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage

      - name: Codecov
        run: yarn codecov -F windows
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
